rules = [
  DisableSyntax,
  LeakingImplicitClassVal,
  OrganizeImports
]

DisableSyntax.noVars = true
DisableSyntax.noThrows = false
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true

OrganizeImports {
  targetDialect = Scala3
  groupedImports = Merge
  removeUnused = true
}
